"""
Storage facade. Delegates to per-space JSON storage (storage.py).
Migrates from legacy cinderella.json/cinderella.db on first run.
All space-scoped functions take chat_id as first argument.
"""

from cinderella.storage import (
    ensure_db_dir,
    get_connection,
    init_db,
    get_or_create_space,
    space_has_zero_rooms,
    is_setup_reminder_silenced,
    set_silence,
    mark_setup_reminder_sent,
    get_spaces_for_setup_reminder,
    add_seen_in_group,
    get_seen_in_group,
    get_or_create_group_chat,
    set_bot_introduced,
    get_space_settings,
    save_space_settings,
    space_has_setup,
    load_config,
    save_config,
    sync_flatmates_from_config,
    sync_rooms_from_config,
    replace_flatmate,
    reshuffle_phrase_orders,
    get_and_advance_phrase,
    set_flatmate_telegram_id,
    get_active_flatmates,
    get_rooms,
    add_room,
    update_room_times,
    remove_room,
    add_member,
    remove_member,
    get_monthly_stats,
    get_cleaning_count_per_flatmate,
    get_effective_cleaning_count_per_flatmate,
    record_cleaning,
    get_pending_assignments_for_date,
    set_remind_on,
    has_assignments_for_week,
    get_assignments_for_week,
    create_assignment,
    update_assignment_status,
    increment_reminder_count,
    get_assignment_by_id,
    get_flatmate_by_username,
    get_flatmate_with_fewest_cleanings_excluding,
    get_chat_ids_with_bot_introduced,
    get_full_cleaning_history,
    get_room_by_name,
    get_pending_assignment_for_room_in_week,
)
