"""
Storage facade. Delegates to JSON storage (storage.py).
Migrates from SQLite on first run if cinderella.db exists.
"""

from cinderella.storage import (
    ensure_db_dir,
    get_connection,
    init_db,
    save_config,
    load_config,
    sync_flatmates_from_config,
    replace_flatmate,
    reshuffle_phrase_orders,
    get_and_advance_phrase,
    set_flatmate_telegram_id,
    sync_rooms_from_config,
    get_active_flatmates,
    get_rooms,
    get_monthly_stats,
    get_cleaning_count_per_flatmate,
    get_effective_cleaning_count_per_flatmate,
    record_cleaning,
    get_or_create_group_chat,
    set_bot_introduced,
    get_pending_assignments_for_date,
    set_remind_on,
    has_assignments_for_week,
    get_assignments_for_week,
    create_assignment,
    update_assignment_status,
    increment_reminder_count,
    get_assignment_by_id,
    get_flatmate_by_username,
    get_flatmate_with_fewest_cleanings_excluding,
    get_chat_ids_with_bot_introduced,
    get_full_cleaning_history,
    get_room_by_name,
    get_pending_assignment_for_room_in_week,
)
